[2024-07-23 17:18:02,374: INFO: main: welcome to our custom log]
[2024-07-23 17:18:26,937: INFO: main: welcome to our custom log]
[2024-07-24 11:10:32,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:11:46,494: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:12:53,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:13:15,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:15:58,817: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:16:34,906: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:17:24,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:17:24,719: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 11:17:24,719: INFO: common: created directory at: artifacts]
[2024-07-24 11:17:24,724: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 11:17:24,726: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:18:01,576: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:39:30,709: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:39:30,724: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\anaconda3\envs\kidney-py3-TF2.0\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:40:18,984: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:40:18,984: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:42:25,788: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:42:25,788: ERROR: main: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2]
Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\main.py", line 14, in <module>
    data_ingestion.main()
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\config\configuration.py", line 12, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 37, in read_yaml
    raise e
  File "c:\users\asus\desktop\kidney-disease-classification-deep-learning-project\kidney-disease-classification1\src\cnnClassifier\utiles\common.py", line 31, in read_yaml
    content = yaml.safe_load(yaml_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "config\config.yaml", line 10, column 1
could not find expected ':'
  in "config\config.yaml", line 22, column 2
[2024-07-24 11:43:18,769: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 11:43:18,787: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 11:43:18,788: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 11:43:18,788: INFO: common: created directory at: artifacts]
[2024-07-24 11:43:18,788: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 11:43:18,788: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:44:06,055: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 11:44:06,951: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-24 12:34:15,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:34:15,178: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:34:15,178: INFO: common: created directory at: artifacts]
[2024-07-24 12:45:56,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:45:56,578: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:45:56,579: INFO: common: created directory at: artifacts]
[2024-07-24 12:48:44,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:48:44,117: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:48:44,119: INFO: common: created directory at: artifacts]
[2024-07-24 12:55:24,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:55:24,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:55:24,015: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:18,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:18,141: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:18,141: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:26,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:26,027: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:26,028: INFO: common: created directory at: artifacts]
[2024-07-24 12:56:51,669: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:56:51,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:56:51,675: INFO: common: created directory at: artifacts]
[2024-07-24 12:57:09,999: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:57:09,999: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:57:10,003: INFO: common: created directory at: artifacts]
[2024-07-24 12:57:48,270: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 12:57:48,271: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 12:57:48,276: INFO: common: created directory at: artifacts]
[2024-07-24 13:01:33,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:01:33,193: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:01:33,196: INFO: common: created directory at: artifacts]
[2024-07-24 13:05:51,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:05:51,156: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:05:51,156: INFO: common: created directory at: artifacts]
[2024-07-24 13:06:02,601: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:06:02,604: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:06:02,606: INFO: common: created directory at: artifacts]
[2024-07-24 13:06:36,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:06:36,751: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:06:36,753: INFO: common: created directory at: artifacts]
[2024-07-24 13:07:08,577: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:07:08,580: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:07:08,582: INFO: common: created directory at: artifacts]
[2024-07-24 13:13:28,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:13:28,805: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:13:28,806: INFO: common: created directory at: artifacts]
[2024-07-24 13:13:41,849: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:13:41,853: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:13:41,854: INFO: common: created directory at: artifacts]
[2024-07-24 13:14:03,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:14:03,745: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:14:03,747: INFO: common: created directory at: artifacts]
[2024-07-24 13:14:53,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:14:53,544: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:14:53,545: INFO: common: created directory at: artifacts]
[2024-07-24 13:18:22,458: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:18:22,460: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:18:22,461: INFO: common: created directory at: artifacts]
[2024-07-24 13:20:41,043: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:20:41,046: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:20:41,048: INFO: common: created directory at: artifacts]
[2024-07-24 13:23:50,533: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:23:50,536: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:23:50,538: INFO: common: created directory at: artifacts]
[2024-07-24 13:24:37,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:24:37,995: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:24:37,996: INFO: common: created directory at: artifacts]
[2024-07-24 13:25:09,594: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:25:09,598: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:25:09,599: INFO: common: created directory at: artifacts]
[2024-07-24 13:25:51,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:25:51,951: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:25:51,953: INFO: common: created directory at: artifacts]
[2024-07-24 13:27:26,563: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:27:26,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:27:26,567: INFO: common: created directory at: artifacts]
[2024-07-24 13:29:20,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:29:20,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:29:20,282: INFO: common: created directory at: artifacts]
[2024-07-24 13:32:42,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:32:42,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:32:42,463: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:16,978: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:41:16,981: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:41:16,982: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:31,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 13:41:31,859: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 13:41:31,860: INFO: common: created directory at: artifacts]
[2024-07-24 13:41:31,862: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-24 13:42:10,741: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:01:29,770: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-07-24 14:01:29,773: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:01:29,774: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:01:29,774: INFO: common: created directory at: artifacts]
[2024-07-24 14:01:29,776: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-24 14:01:29,777: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:02:10,472: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1SJMu4dDBgoltHNZ8iOLB9zygSAGtIDG6/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-07-24 14:02:11,329: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-07-24 14:02:11,330: INFO: main: *******************]
[2024-07-24 14:02:11,330: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-07-24 14:02:11,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-24 14:02:11,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-24 14:02:11,335: INFO: common: created directory at: artifacts]
[2024-07-24 14:02:11,335: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-07-24 14:02:12,095: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-07-24 14:02:12,705: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
